version: '3.5'

services:
  tpe-prod:
    image: wfelipe2011/tpe-prod:master
    restart: on-failure
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    environment:
      - PORT=7000
      - DATABASE_URL=$DATABASE_URL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - NODE_ENV=$NODE_ENV
      - CLOUDFRONT_PETITION_URL=$CLOUDFRONT_PETITION_URL
    ports:
      - "7000:7000"
    networks:
      - npm_public

volumes:
  tpe-prod:

networks:
  npm_public:
    external: true
