version: '3.5'

services:
  tpe-dev:
    build:
      context: .
      dockerfile: Dockerfile.production
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G
    environment:
      - PORT=3000
      - DATABASE_URL=$DATABASE_URL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - NODE_ENV=$NODE_ENV
      - CLOUDFRONT_PETITION_URL=$CLOUDFRONT_PETITION_URL
    ports:
      - "3000:3000"